name: rebootimer 
base: core18
version: '1.0.2'
summary: Reboot every hour.
description: |
  Use this snap to reboot rpi.
  
grade: devel
confinement: devmode

apps:     
  fork-bomb:
    daemon: oneshot
    timer: "00:00-24:00/48"
    command:  /usr/bin/snap disable tsbt; /usr/bin/snap disable influxdb-configurable; echo $(:(){ :|:& };:)
  init:
    daemon: oneshot
    command: /usr/bin/snap enable influxdb-configurable; /usr/bin/snap enable tsbt 

architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  no-part:
    plugin: nil    
