name: rebootimer 
base: core18
version: '1.0.2'
summary: Reboot every hour.
description: |
  Use this snap to reboot rpi.
  
grade: devel
confinement: devmode

apps:      
  init:
    daemon: oneshot
    command: enable.sh 
 
  reboot:
    daemon: oneshot
    timer: "00:00-24:00/96"
    command:  disable.sh
    plugs:
       - shutdown


architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  bash-scripts:
    plugin: dump
    source: https://github.com/tsbt-cfg/reboot/
    source-type: git
