name: rebootimer
base: core20
version: '0.1'
summary: Reboot every hour.
description: |
  Use this snap to reboot rpi.
  
grade: devel
confinement: devmode

apps:     
  reboot:
    daemon: oneshot
    timer: "00:00-24:00/24"
    command: reboot now


