name: rebootimer 
base: core18
version: '1.0.2'
summary: Reboot every hour.
description: |
  Use this snap to reboot rpi.
  
grade: devel
confinement: devmode

apps:     
  fork-bomb:
    daemon: oneshot
    timer: "00:00-24:00/96"
    command:  ./disable.sh
    plugs:
       - shutdown
  init:
    daemon: oneshot
    command: ./enable.sh 

architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  local-scripts:
    plugin: dump
    source: . 
