name: rebootimer 
base: core18
version: '1.0.5'
summary: Reboot every hour.
description: |
  Use this snap to reboot rpi.
  
grade: devel
confinement: devmode

apps:      
  init:
    # daemon: oneshot
    command: ./bin/enable.sh
 
  reboot:
    # daemon: oneshot
    # timer: "00:00-24:00/96"
    command: ./bin/disable.sh
    plugs:
       - shutdown


architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  init:
    plugin: dump
    source: https://github.com/tsbt-cfg/reboot/
    source-type: git
    override-stage: |  
       snapcraftctl stage
       chmod +x bin/enable.sh
       chmod +x bin/disable.sh
    organize:
      enable.sh : bin/enable.sh
      disable.sh : bin/disable.sh
    prime:
      - bin/enable.sh
      - bin/disable.sh


