name: rebootimer
base: core18
version: '1.0'
summary: Reboot every hour.
description: |
  Use this snap to reboot rpi.
  
grade: devel
confinement: devmode

apps:     
  reboot:
    daemon: oneshot
    timer: "00:00-24:00/24"
    command-chain:
    -COUNT=$((COUNT+1))
    -if [ "$COUNT" -eq 2 ]; then shutdown -r now fi
    command: echo "shutdown"
    plugs: [shutdown]
  setcounter:
    daemon:oneshot
    command: COUNT=0
    before: reboot
     
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  no-part:
    plugin: nil    
